# Generated by Django 4.2.9 on 2024-02-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('adhesion', models.IntegerField(default=True)),
            ],
            options={
                'verbose_name': 'Adherent',
            },
        ),
        migrations.CreateModel(
            name='GearCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Categorie Materiel',
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('toRepair', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.gearcat')),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('returnTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('gear1IsDamaged', models.BooleanField(default=False)),
                ('gear2IsDamaged', models.BooleanField(default=False)),
                ('adherent1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adherent1', to='gestion.adherent')),
                ('adherent2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adherent2', to='gestion.adherent')),
                ('gear1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gear1', to='gestion.gear')),
                ('gear2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gear2', to='gestion.gear')),
            ],
            options={
                'verbose_name': 'Emprunt',
            },
        ),
    ]
