# Generated by Django 4.2.9 on 2024-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentals',
            options={'verbose_name': 'Emprunt'},
        ),
        migrations.AddField(
            model_name='rentals',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
