# Generated by Django 4.2.9 on 2024-01-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adherent',
            old_name='nom',
            new_name='name',
        ),
    ]
