# Generated by Django 4.2.9 on 2024-02-19 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 10, 2, 42, 813939, tzinfo=datetime.timezone.utc)),
        ),
    ]
