# Generated by Django 4.2.9 on 2024-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_adherent_adhesion_alter_adherent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='firstname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='surname',
            field=models.CharField(max_length=64),
        ),
    ]
