# Generated by Django 4.2.9 on 2024-02-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_rentals_options_rentals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='adherent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adherent2', to='gestion.adherent'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gear2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gear2', to='gestion.gear'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='returnTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
