# Generated by Django 4.2.9 on 2024-01-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_nom_adherent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adherent',
            old_name='name',
            new_name='firstname',
        ),
    ]
