# Generated by Django 4.2.9 on 2024-02-19 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_emprunt_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 16, 23, 50, 689179, tzinfo=datetime.timezone.utc)),
        ),
    ]
