# Generated by Django 4.2.9 on 2024-02-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_rentals_adherent2_alter_rentals_gear2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='date',
        ),
    ]
