# Generated by Django 4.2.9 on 2024-01-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_material_photo_alter_adherent_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Gear',
        ),
    ]
