# Generated by Django 4.2.9 on 2024-01-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_rename_material_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Categorie Materiel',
            },
        ),
        migrations.AlterModelOptions(
            name='adherent',
            options={'verbose_name': 'Adherent'},
        ),
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name': 'Gear'},
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.gearcat'),
        ),
    ]
