# Generated by Django 4.2.9 on 2024-01-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_gearcat_alter_adherent_options_alter_gear_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.gearcat'),
        ),
    ]
